"""
Django settings for survey_and_poll project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import environ
import os
import sys
import dj_database_url
from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------
# Environment setup
# ------------------------------------------------------------------
env = environ.Env(
    DEBUG=(bool, False)
)

# Load .env file depending on run context
env = environ.Env()
if "runserver" in sys.argv:
    env_file = BASE_DIR / ".env.dev"
else:
    env_file = BASE_DIR / ".env.prod"

if env_file.exists():
    environ.Env.read_env(env_file)
else:
    raise FileNotFoundError(f"{env_file} not found. Please create it.")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m65a-i4b#py$c4qy2p%o+l)qim7qhv6ya1ytq^k*+(gn8*!mcu'

# ------------------------------------------------------------------
# General settings
# ------------------------------------------------------------------
SECRET_KEY = env("SECRET_KEY", default="insecure-default-key")
DEBUG = env("DEBUG", default=False, cast=bool)

def get_list_from_env(name, default=""):
    """Safely split comma-separated env vars into a list."""
    value = env(name, default=default)
    if not value:
        return []
    return [v.strip() for v in value.split(",") if v.strip()]

ALLOWED_HOSTS = ['*']
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

CORS_ALLOWED_ORIGINS = get_list_from_env("CORS_ALLOWED_ORIGINS")
if DEBUG and not CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:5173",
    ]

CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'https://*.yourdomain.com',
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ]
    CSRF_TRUSTED_ORIGINS = list(set(CSRF_TRUSTED_ORIGINS))

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'authentication',
    'polls',
    'users',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    "corsheaders",
    "drf_spectacular",
    "drf_spectacular_sidecar",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'survey_and_poll.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'survey_and_poll.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

USE_SQLITE = env.bool("USE_SQLITE", default=True)

if USE_SQLITE:
    # Production / PythonAnywhere
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Render development (dj database)
    DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "polls.permissions.ReadOnlyOrAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# ------------------------------------------------------------------
# Custom user model
# 
AUTH_USER_MODEL = 'users.CustomUser'

# ------------------------------------------------------------------
# Spectacular / Swagger
# ------------------------------------------------------------------
SPECTACULAR_SETTINGS = {
    "TITLE": "Poll System API",
    "DESCRIPTION": "Backend API for creating polls, voting, and managing results.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [
        {"BasicAuth": []},
        {"SessionAuth": []},
    ],
    "COMPONENT_SPLIT_REQUEST": True,
    "COMPONENTS": {
        "securitySchemes": {
            "BasicAuth": {
                "type": "http",
                "scheme": "basic",
                "description": "Use your username and password to authenticate.",
            },
            "SessionAuth": {
                "type": "apiKey",
                "in": "cookie",
                "name": "sessionid",
                "description": "Session-based authentication using Django's session cookie.",
            },
        }
    },
    "TAGS": [
        {"name": "Polls", "description": "Poll management endpoints"},
        {"name": "Options", "description": "Poll options"},
        {"name": "Votes", "description": "Vote submission"},
        {"name": "Auth", "description": "User authentication and registration"},
    ],
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "oauth2RedirectUrl": "/api-auth/login/",
    },
}
